FROM busybox:ubuntu-14.04
MAINTAINER Slavik Markovich <slavik@demisto.com>

COPY ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY g-bot.conf /etc/g-bot.conf
COPY alfred /bin/alfred

CMD alfred -conf=/etc/g-bot.conf
